import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/contexts/appContext";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <div className="w-full bg-neutral-800 p-5 border-b-neutral-500 border-b-2 font-bold flex justify-between">
            <div>Webauthn</div>
            <div className="flex">
              <div className="mr-3"><Link href={'/'}>Home</Link></div>
              <div className="mr-3"><Link href={'/user/profile'}>Profile</Link></div>
            </div>
          </div>
          <div className="py-10 px-6">
          {children}
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
